"""Markdown report — useful for pasting into issue trackers."""

from __future__ import annotations

from stbox.models import ScanResult, Severity


_SEV_BADGE = {
    Severity.CRITICAL: "🟥 CRITICAL",
    Severity.HIGH:     "🟧 HIGH",
    Severity.MEDIUM:   "🟨 MEDIUM",
    Severity.LOW:      "🟩 LOW",
    Severity.INFO:     "🟦 INFO",
}


def render_markdown(r: ScanResult) -> str:
    lines: list[str] = []
    lines.append(f"# stbox scan report — {r.target}")
    lines.append("")
    lines.append(f"**Mode:** `{r.mode.value}`  ")
    lines.append(f"**Started:** {r.started_at.isoformat()}  ")
    if r.finished_at:
        lines.append(f"**Finished:** {r.finished_at.isoformat()}  ")
    lines.append("")

    counts = r.counts_by_severity()
    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev, c in counts.items():
        lines.append(f"| {sev.upper()} | {c} |")
    lines.append("")

    if r.scope_notes:
        lines.append("## Scope notes")
        for n in r.scope_notes:
            lines.append(f"- {n}")
        lines.append("")

    if r.subdomains:
        lines.append(f"## Subdomains ({len(r.subdomains)})")
        for s in r.subdomains[:100]:
            lines.append(f"- `{s}`")
        if len(r.subdomains) > 100:
            lines.append(f"- *(+{len(r.subdomains) - 100} more)*")
        lines.append("")

    if r.live_hosts:
        lines.append(f"## Live hosts ({len(r.live_hosts)})")
        for h in r.live_hosts[:100]:
            lines.append(f"- `{h}`")
        lines.append("")

    if r.tech_stack:
        lines.append("## Technology fingerprint")
        for host, techs in r.tech_stack.items():
            lines.append(f"- **{host}**: {', '.join(techs)}")
        lines.append("")

    lines.append("## Findings")
    lines.append("")
    for f in r.sorted_findings():
        badge = _SEV_BADGE.get(f.severity, f.severity.value)
        lines.append(f"### {badge} — {f.title}")
        lines.append(f"*tool:* `{f.tool}` · *target:* `{f.target}`")
        if f.cve:
            lines.append(f"*CVE:* {', '.join(f.cve)}")
        if f.cwe:
            lines.append(f"*CWE:* {', '.join(f.cwe)}")
        if f.description:
            lines.append("")
            lines.append(f.description)
        if f.references:
            lines.append("")
            for ref in f.references[:5]:
                lines.append(f"- {ref}")
        lines.append("")

    lines.append("## Tool runs")
    lines.append("")
    lines.append("| Tool | Status | Duration | Findings | Exit |")
    lines.append("|------|--------|----------|----------|------|")
    for t in r.tool_runs:
        d = f"{t.duration_seconds:.1f}s" if t.duration_seconds else "-"
        lines.append(
            f"| {t.tool} | {t.status} | {d} | {t.findings_count} | {t.exit_code} |"
        )
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by stbox — https://github.com/JaviiHernandez/SecurityToolbox-CLI*")

    return "\n".join(lines)
